### ISSUE TITLE
Support to other languages?

### ISSUE THREAD

**Issue by lhfaria** [machinalis/quepy#18]
Hi folks, is there any chance there's a simple way to implement other languages support? Cheers

**Comment by rafacarrascosa** [comment]
Hi, other languages like SQL? Or other languages like Spanish or Portuguese?

**Comment by lhfaria** [comment]
Yeap, I meant languages like Portuguese.

_Leandro Faria_about.me/lhfaria
553192132680

2014-10-09 15:01 GMT-03:00 rafacarrascosa notifications@github.com:

**Comment by rafacarrascosa** [comment]
Each question in natural language must be tokenized, lematized and POS tagged. Currently this is done [here](https://github.com/machinalis/quepy/blob/develop/quepy/nltktagger.py#L34) using nltk.
If you can provide a similar function for Portuguese then you're done!
Do you know of a natural language tool for Portuguese that can do that?

**Comment by rafacarrascosa** [comment]
Expired!
