### ISSUE TITLE
Freebase is shutting down

### ISSUE THREAD

**Issue by thedrow** [machinalis/quepy#21]
MQL will not be available in June 30, 2015.
It will be replaced with Wikidata.

See post [here](https://plus.google.com/109936836907132434202/posts/bu3z2wVqcQc)

**Comment by rafacarrascosa** [comment]
Thank you @thedrow, I guess that would deprecate MQL entirely... do you know of any other DB that accepts MQL as query language?

**Comment by thedrow** [comment]
Nope. Not really.

**Comment by ghost** [comment]
There may be a opportunity to create own database, so there could be a chance to create a knowledge engine, such as Wolfram Alpha has.

**Comment by thedrow** [comment]
They are moving all of their data to wikidata.
