### ISSUE TITLE
The quepy version on pypi is missing docopt as a requirement

### ISSUE THREAD

**Issue by rafacarrascosa** [machinalis/quepy#24]
That, docopt is missing as a requirement

**Comment by iScienceLuvr** [comment]
what is the importance of docopt for the module?

**Comment by rafacarrascosa** [comment]
It's needed by the `quepy` command line utility to parse command line arguments.
The version on github already has this requirement, so as a hotfix you can do:

```
pip install -e path/to/quepy/repo
```

to have it installed.

**Comment by iScienceLuvr** [comment]
@rafacarrascosa interesting, because I downloaded quepy using pip install and it works fine with command line questions. Anyway, I did make a pull request to add that docopt is a requirement in the docs.

**Comment by rafacarrascosa** [comment]
Thanks for the PR! credits to you @iScienceLuvr  :)
