### ISSUE TITLE
Countries aren't the only thing with capitols

### ISSUE THREAD

**Issue by tfmorris** [machinalis/quepy#3]
When I ask "What is the capital of Massachusetts?" it fails to find an answer because it thinks Massachusetts is a country.

**Comment by rafacarrascosa** [comment]
Thank you Tom, we'll look into modifying the query handler for that question.

**Comment by tfmorris** [comment]
Thanks for looking into this, but note that the original query was "What is the capitol?" not "What is the population?" I'll retest with the new code when I get a chance, but it may be a while.

**Comment by tfmorris** [comment]
In Freebase terms, the property that you want is `/location/administrative_division/capital` and the corresponding type is `/location/administrative_division`. I'm not sure what the equivalents would be for DBpedia.
