### ISSUE TITLE
Error in Demo

### ISSUE THREAD

**Issue by jithurjacob** [machinalis/quepy#35]
Hi in the online demo given at http://quepy.machinalis.com/ I'm getting result for "what is the plot of Titanic?" but not for "what is the plot of titanic?"

Is this expected?

**Comment by rafacarrascosa** [comment]
Hi, yes, this is expected to happen.
It is very likely that "titanic" is interpreted by the POS tagger as an
adjective (pertaining to titans) and "Titanic" is interpreted as a proper
noun.

Regards,

Rafael

**Comment by jithurjacob** [comment]
Can we actually solve this by training our own tagger with movie names. Pardon me if I'm wrong I'm new to NLP.

**Comment by rafacarrascosa** [comment]
That would be one way to do it, yes.
If you know your questions will only be on a specific domain (ex. movies) there are more things you can do, like relaxing the need for a proper noun to be part of the movie title.
