### ISSUE TITLE
Missing wrapper on Windows install

### ISSUE THREAD

**Issue by tfmorris** [machinalis/quepy#4]
To work on Windows, you'll need a quepy.bat wrapper for the quepy Python script.  All the other things in my Scripts directory have them, but I'm not sure what is needed to get the installer to create it (or if you have to do it yourself).  I installed using pip, not easy_install, if it makes a difference.

**Comment by rafacarrascosa** [comment]
Mmm... and besides that it's working? I'm amazed! We were not even considering Windows when we wrote it.
I'll check if one of the guys at the office has a Windows computer to fix the deploy scritps.
Thank you Tom!

**Comment by tfmorris** [comment]
Yup, seems to work fine.  Of course, I'd already installed numpy using one
of the pre-built 64-bit binaries (otherwise you need a MingW based build
environment to install Python modules with C extensions).  Python IS
supposed to be portable after all... :-)
