### ISSUE TITLE
Broken NLTK setup

### ISSUE THREAD

**Issue by TestSubjector** [machinalis/quepy#40]
While running `quepy nltkdata /some/path`downloads the resources "wordnet" and "maxent_treebank
_pos_tagger", trying to run the applicaion gives the following error:

> Resource u'taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle' not found.  Please use the NLTK Downloader to obtain the resource:  >>> nltk.download()

I believe this is because of the perceptron tagger being made the default tagger in the [nltk project](https://github.com/nltk/nltk/commit/0239a3995a52bcd56dc8e07438c0efd375d40de9), which is a dependency for quepy.

**Comment by rafacarrascosa** [comment]
Thanks!
